# Fuentes de modelización

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Limpieza de los datos

### Carga de los datos después de la limpieza

In [2]:
datos_limpios = pd.read_csv('/Users/melo/Downloads/model_data.csv')
datos_limpios

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,estu_yearnacimiento
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,No,No,No,A2,332,2000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Ninguno,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,2001.0
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0

### Creación de las categorías del desempeño en el icfes según percentiles

In [3]:
datos_limpios['Ingresa'] = np.where(datos_limpios['punt_global'] >= 300, 1, 0)
datos_limpios

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,estu_yearnacimiento,Ingresa
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0,0
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0,0
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0,0
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0,0
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Estrato 2,3 a 4,No,No,No,No,A2,332,2000.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,2001.0,0
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0,0
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0,0
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0,0
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0,0

### Transformación de los datos del año de nacimiento a la edad del candidato

In [4]:
datos_limpios['estu_edad'] = 2019 - datos_limpios['estu_yearnacimiento']
datos_limpios = datos_limpios.drop(columns=['estu_yearnacimiento'])
datos_limpios

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,Ingresa,estu_edad
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.0
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.0
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.0
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.0
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Estrato 2,3 a 4,No,No,No,No,A2,332,1,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,0,18.0
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.0
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.0
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.0
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.0

In [5]:
pd.set_option('display.float_format', '{:.2f}'.format)
datos_limpios.describe()

       punt_global    Ingresa  estu_edad
count   1027084.00 1027084.00 1027076.00
mean        247.87       0.17      17.76
std          51.04       0.38       3.55
min           0.00       0.00       0.00
25%         209.00       0.00      17.00
50%         245.00       0.00      17.00
75%         284.00       0.00      18.00
max         477.00       1.00     119.00

### Eliminación de outliers (presentan el examen personas entre 15 y 40 años)

In [6]:
datos_filtrados = datos_limpios[(datos_limpios['estu_edad'] >= 15) & (datos_limpios['estu_edad'] <= 40)]
datos_filtrados

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,Ingresa,estu_edad
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.00
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.00
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.00
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.00
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Estrato 2,3 a 4,No,No,No,No,A2,332,1,19.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,0,18.00
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.00
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.00
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.00
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.00

In [7]:
datos_filtrados.describe()

       punt_global    Ingresa  estu_edad
count   1020784.00 1020784.00 1020784.00
mean        248.13       0.17      17.61
std          50.97       0.38       2.22
min           0.00       0.00      15.00
25%         210.00       0.00      17.00
50%         245.00       0.00      17.00
75%         284.00       0.00      18.00
max         477.00       1.00      40.00

In [8]:
datos_filtrados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020784 entries, 0 to 1027083
Data columns (total 23 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   estu_tipodocumento    1020784 non-null  object
 1   cole_area_ubicacion   1020784 non-null  object
 2   cole_bilingue         1020784 non-null  object
 3   cole_calendario       1020784 non-null  object
 4   cole_caracter         1020784 non-null  object
 5   cole_genero           1020784 non-null  object
 6   cole_jornada          1020784 non-null  object
 7   cole_naturaleza       1020784 non-null  object
 8   estu_depto_reside     1020784 non-null  object
 9   estu_genero           1020784 non-null  object
 10  fami_cuartoshogar     1020784 non-null  object
 11  fami_educacionmadre   1020784 non-null  object
 12  fami_educacionpadre   1020784 non-null  object
 13  fami_estratovivienda  1020784 non-null  object
 14  fami_personashogar    1020784 non-null  object
 15  fami_tieneautomovil   1020784 non-null  object
 16  fami_tienecomputador  1020784 non-null  object
 17  fami_tieneinternet    1020784 non-null  object
 18  fami_tienelavadora    1020784 non-null  object
 19  desemp_ingles         1020784 non-null  object
 20  punt_global           1020784 non-null  int64
 21  Ingresa               1020784 non-null  int64
 22  estu_edad             1020784 non-null  float64
dtypes: float64(1), int64(2), object(20)
memory usage: 186.9+ MB

## Selección de variables

### Separación de variables en numéricas y categóricas (las categóricas se separan en tres grupos: cole, estu, fami)

In [9]:
var_cat = datos_limpios.select_dtypes(include=['object']).columns
var_cat_cole = [col for col in var_cat if col.startswith('cole')]
var_cat_estu = [col for col in var_cat if col.startswith('estu')]
var_cat_estu.append('desemp_ingles')
var_cat_fami = [col for col in var_cat if col.startswith('fami')]
var_num = 'estu_edad'
target = 'punt_global'

In [10]:
for col in var_cat:
    print(datos_filtrados[col].value_counts())

estu_tipodocumento
TI     852248
CC     161896
CR       2962
CE       2004
NES      1006
PEP       428
PE        172
RC         38
V          14
CCB         8
PC          8
Name: count, dtype: int64
cole_area_ubicacion
URBANO    862338
RURAL     158446
Name: count, dtype: int64
cole_bilingue
N           849330
Faltante    161282
S            10172
Name: count, dtype: int64
cole_calendario
A       1013406
OTRO       5390
B          1988
Name: count, dtype: int64
cole_caracter
ACADÉMICO            557152
TÉCNICO/ACADÉMICO    340630
TÉCNICO              110026
NO APLICA             12976
Name: count, dtype: int64
cole_genero
MIXTO        987182
FEMENINO      26052
MASCULINO      7550
Name: count, dtype: int64
cole_jornada
MAÑANA      486560
COMPLETA    171900
UNICA       128200
TARDE       111998
SABATINA     64976
NOCHE        57150
Name: count, dtype: int64
cole_naturaleza
OFICIAL       779258
NO OFICIAL    241526
Name: count, dtype: int64
estu_depto_reside
BOGOTÁ             159854
ANTIOQUIA          138582
VALLE               72446
CUNDINAMARCA        68190
ATLANTICO           59670
SANTANDER           47910
BOLIVAR             45746
CORDOBA             37804
BOYACA              31946
TOLIMA              30892
NARIÑO              30672
MAGDALENA           30476
NORTE SANTANDER     30190
HUILA               26212
CAUCA               25192
CESAR               24614
META                23376
SUCRE               20284
RISARALDA           20218
CALDAS              19746
LA GUAJIRA          15940
QUINDIO             11814
CASANARE            11288
CHOCO                8764
CAQUETA              8622
PUTUMAYO             7262
ARAUCA               6388
GUAVIARE             1874
AMAZONAS             1402
SAN ANDRES           1190
VICHADA               932
VAUPES                558
GUAINIA               490
EXTRANJERO            240
Name: count, dtype: int64
estu_genero
F    553090
M    467694
Name: count, dtype: int64
fami_cuartoshogar
Tres          412164
Dos           358882
Cuatro        133978
Uno            52276
Cinco          41342
Seis o mas     22142
Name: count, dtype: int64
fami_educacionmadre
Secundaria (Bachillerato) completa      272116
Primaria incompleta                     157038
Secundaria (Bachillerato) incompleta    151104
Educación profesional completa          107930
Técnica o tecnológica completa          105286
Primaria completa                       105140
Técnica o tecnológica incompleta         31628
Educación profesional incompleta         24602
Ninguno                                  24218
Postgrado                                21468
No sabe                                  18164
No Aplica                                 2090
Name: count, dtype: int64
fami_educacionpadre
Secundaria (Bachillerato) completa      235928
Primaria incompleta                     199176
Secundaria (Bachillerato) incompleta    141040
Primaria completa                       106636
Educación profesional completa           91860
Técnica o tecnológica completa           70272
No sabe                                  63432
Ninguno                                  38420
Técnica o tecnológica incompleta         21646
Educación profesional incompleta         20106
Postgrado                                18732
No Aplica                                13536
Name: count, dtype: int64
fami_estratovivienda
Estrato 2    409802
Estrato 1    319354
Estrato 3    216848
Estrato 4     51430
Estrato 5     15970
Estrato 6      7380
Name: count, dtype: int64
fami_personashogar
3 a 4      506636
5 a 6      322610
7 a 8       84230
1 a 2       74506
9 o más     32802
Name: count, dtype: int64
fami_tieneautomovil
No    777336
Si    243448
Name: count, dtype: int64
fami_tienecomputador
Si    581910
No    438874
Name: count, dtype: int64
fami_tieneinternet
Si    624932
No    395852
Name: count, dtype: int64
fami_tienelavadora
Si    789150
No    231634
Name: count, dtype: int64
desemp_ingles
A-    492006
A1    293300
A2    153584
B1     67588
B+     14306
Name: count, dtype: int64

In [11]:
datos_finales = datos_filtrados.copy()
datos_finales['estu_tipodocumento'] = datos_filtrados['estu_tipodocumento'].apply(
    lambda x: x if x in ['CC', 'TI'] else 'Otro'
)

In [12]:
datos_modelo = datos_finales.copy()
datos_modelo = datos_modelo.drop(columns=['cole_bilingue', 'cole_caracter', 'punt_global'])
datos_modelo

,estu_tipodocumento,cole_area_ubicacion,cole_calendario,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,Ingresa,estu_edad
0,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,19.00
1,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,19.00
2,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,19.00
3,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,19.00
4,CC,URBANO,A,MIXTO,UNICA,OFICIAL,VALLE,F,Dos,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,No,No,No,A2,1,19.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,A,MIXTO,SABATINA,OFICIAL,TOLIMA,F,Tres,Primaria incompleta,Ninguno,Estrato 2,5 a 6,No,Si,Si,Si,A-,0,18.00
1027080,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,17.00
1027081,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,17.00
1027082,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,19.00
1027083,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,19.00

In [13]:
datos_modelo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020784 entries, 0 to 1027083
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   estu_tipodocumento    1020784 non-null  object
 1   cole_area_ubicacion   1020784 non-null  object
 2   cole_calendario       1020784 non-null  object
 3   cole_genero           1020784 non-null  object
 4   cole_jornada          1020784 non-null  object
 5   cole_naturaleza       1020784 non-null  object
 6   estu_depto_reside     1020784 non-null  object
 7   estu_genero           1020784 non-null  object
 8   fami_cuartoshogar     1020784 non-null  object
 9   fami_educacionmadre   1020784 non-null  object
 10  fami_educacionpadre   1020784 non-null  object
 11  fami_estratovivienda  1020784 non-null  object
 12  fami_personashogar    1020784 non-null  object
 13  fami_tieneautomovil   1020784 non-null  object
 14  fami_tienecomputador  1020784 non-null  object
 15  fami_tieneinternet    1020784 non-null  object
 16  fami_tienelavadora    1020784 non-null  object
 17  desemp_ingles         1020784 non-null  object
 18  Ingresa               1020784 non-null  int64
 19  estu_edad             1020784 non-null  float64
dtypes: float64(1), int64(1), object(18)
memory usage: 163.5+ MB

In [14]:
for col in datos_modelo.columns:
    print(f"{col}: {datos_modelo[col].nunique()} valores únicos")

estu_tipodocumento: 3 valores únicos
cole_area_ubicacion: 2 valores únicos
cole_calendario: 3 valores únicos
cole_genero: 3 valores únicos
cole_jornada: 6 valores únicos
cole_naturaleza: 2 valores únicos
estu_depto_reside: 34 valores únicos
estu_genero: 2 valores únicos
fami_cuartoshogar: 6 valores únicos
fami_educacionmadre: 12 valores únicos
fami_educacionpadre: 12 valores únicos
fami_estratovivienda: 6 valores únicos
fami_personashogar: 5 valores únicos
fami_tieneautomovil: 2 valores únicos
fami_tienecomputador: 2 valores únicos
fami_tieneinternet: 2 valores únicos
fami_tienelavadora: 2 valores únicos
desemp_ingles: 5 valores únicos
Ingresa: 2 valores únicos
estu_edad: 26 valores únicos

## Fuentes de modelización

In [15]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.model_selection import ParameterGrid, ParameterSampler
import mlflow
import keras
from keras import callbacks
from joblib import dump

In [16]:
# Instanciar el scaler
scaler = StandardScaler()

# Escalar solo col1 y col2
datos_modelo['estu_edad'] = scaler.fit_transform(datos_modelo[['estu_edad']])
dump(scaler, 'scaler.pkl')
datos_modelo

,estu_tipodocumento,cole_area_ubicacion,cole_calendario,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,Ingresa,estu_edad
0,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,0.63
1,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,0.63
2,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,0.63
3,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,0.63
4,CC,URBANO,A,MIXTO,UNICA,OFICIAL,VALLE,F,Dos,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,No,No,No,A2,1,0.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,A,MIXTO,SABATINA,OFICIAL,TOLIMA,F,Tres,Primaria incompleta,Ninguno,Estrato 2,5 a 6,No,Si,Si,Si,A-,0,0.18
1027080,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,-0.27
1027081,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,-0.27
1027082,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,0.63
1027083,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,0.63

In [17]:
y = datos_modelo['Ingresa']
datos_X = datos_modelo.drop(columns=['Ingresa'])

In [19]:
X = pd.get_dummies(datos_X, drop_first = True, dtype = int)
dump(X.columns.to_list(), 'X_columns.pkl')

X

,estu_edad,estu_tipodocumento_Otro,estu_tipodocumento_TI,cole_area_ubicacion_URBANO,cole_calendario_B,cole_calendario_OTRO,cole_genero_MASCULINO,cole_genero_MIXTO,cole_jornada_MAÑANA,cole_jornada_NOCHE,...,fami_personashogar_7 a 8,fami_personashogar_9 o más,fami_tieneautomovil_Si,fami_tienecomputador_Si,fami_tieneinternet_Si,fami_tienelavadora_Si,desemp_ingles_A1,desemp_ingles_A2,desemp_ingles_B+,desemp_ingles_B1
0,0.63,0,0,1,0,0,0,1,0,0,...,0,0,1,1,1,1,1,0,0,0
1,0.63,0,0,1,0,0,0,1,0,0,...,0,0,1,1,1,1,1,0,0,0
2,0.63,0,1,1,0,0,0,1,1,0,...,1,0,0,1,1,1,1,0,0,0
3,0.63,0,1,1,0,0,0,1,1,0,...,1,0,0,1,1,1,1,0,0,0
4,0.63,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,0.18,0,1,1,0,0,0,1,0,0,...,0,0,0,1,1,1,0,0,0,0
1027080,-0.27,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1027081,-0.27,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1027082,0.63,0,0,1,0,0,0,1,0,0,...,0,0,1,1,1,1,0,1,0,0
1027083,0.63,0,0,1,0,0,0,1,0,0,...,0,0,1,1,1,1,0,1,0,0

In [ ]:
import numpy as np
from sklearn.utils.class_weight import compute_class_weight

compute_class_weight(class_weight="balanced", classes=np.unique(y), y=y)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.utils import class_weight
import numpy as np

# Asegúrate de que y_train sea un array plano (no one-hot)
y_train_np = np.array(y_train)

# Calcula los pesos de clase
class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_np),
    y=y_train_np
)

# Lo convierte a diccionario: {0: peso_0, 1: peso_1}
class_weights_dict = dict(enumerate(class_weights))
class_weights_dict

In [ ]:
def train_model(parameters, train_X, train_y, test_X, test_y, experiment_name, early_stop):
    
    model = Sequential()
    model.add(Input(shape=(train_X.shape[1],)))
    model.add(Dense(parameters['hidden_units'], activation = parameters['act_func']))
    
    if parameters['layers'] > 1:
        model.add(Dense(parameters['hidden_units'], activation = parameters['act_func']))
    if parameters['layers'] == 3:
        model.add(Dense(parameters['hidden_units'], activation = parameters['act_func']))
        
    model.add(Dense(1, activation='sigmoid'))
    
    if parameters['optimizer'] == 'adam':
        opt = keras.optimizers.Adam(learning_rate = parameters['learning_rate'])
    elif parameters['optimizer'] == 'adagrad':
        opt = keras.optimizers.Adagrad(learning_rate = parameters['learning_rate'])
    elif parameters['optimizer'] == 'sgd':
        opt = keras.optimizers.SGD(learning_rate = parameters['learning_rate'])
    
    model.compile(optimizer = opt, loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    # defina el servidor para llevar el registro de modelos y artefactos
    mlflow.set_tracking_uri('http://127.0.0.1:5000')
    # registre el experimento
    experiment = mlflow.set_experiment(experiment_name)
    
    # Aquí se ejecuta MLflow sin especificar un nombre o id del experimento. MLflow los crea un experimento para este cuaderno por defecto y guarda las características del experimento y las métricas definidas. 
    # Para ver el resultado de las corridas haga click en Experimentos en el menú izquierdo. 
    with mlflow.start_run(experiment_id=experiment.experiment_id):
        
        history = model.fit(train_X, train_y,
                  epochs = parameters['epochs'],
                  batch_size = parameters['batch_size'],
                  validation_split = 0.2,
                  callbacks = [early_stop],
                  class_weight = class_weights_dict,
                  verbose = 0
                  )
        
        #Evaluar el modelo
        eval_model = model.evaluate(test_X, test_y, verbose = 0)
        loss = eval_model[0]
        accuracy = eval_model[1]
        
        y_pred_proba = model.predict(test_X)
        y_pred = (y_pred_proba >= parameters['threshold']).astype(int)
        
        cm = confusion_matrix(test_y, y_pred)
        
        tn = cm[0][0]
        tp = cm[1][1]
        fn = cm[1][0]
        fp = cm[0][1]
        
        pos_precision = tp / (tp + fp) if (tp + fp) != 0 else 0
        neg_precision = tn / (tn + fn) if (tn + fn) != 0 else 0
        pos_recall = tp / (tp + fn) if (tp + fn) != 0 else 0
        neg_recall = tn / (tn + fp) if (tn + fp) != 0 else 0
        error_I = fp / (fp + tn) if (fp + tn) != 0 else 0
        error_II = fn / (fn + tp) if (fn + tp) != 0 else 0
        f1 = (2 * pos_precision * pos_recall) / (pos_precision + pos_recall) if (pos_precision + pos_recall) != 0 else 0
        
        # Log parameters and results
        mlflow.log_params(parameters)
        mlflow.log_metric("accuracy", round(accuracy, 5))
        mlflow.log_metric("test_loss", round(loss, 5))
        mlflow.log_metric("positive_precision", round(pos_precision, 5))
        mlflow.log_metric("negative_precision", round(neg_precision, 5))
        mlflow.log_metric("positive_recall", round(pos_recall, 5))
        mlflow.log_metric("negative_recall", round(neg_recall, 5))
        mlflow.log_metric("F1_score", round(f1, 5))
        mlflow.log_metric("Error_I", round(error_I, 5))
        mlflow.log_metric("Error_II", round(error_II, 5))
        print(f'Loss: {loss}, Accuracy: {accuracy}')
        
        # Log model
        mlflow.tensorflow.log_model(model, "model")
            
    
        return {"model": model, 'history' : history}

In [ ]:
def show_history(hist):
    plt.plot(hist.history['loss'], label='Entrenamiento')
    plt.plot(hist.history['val_loss'], label='Validación')
    plt.xlabel('Época')
    plt.ylabel('Precisión')
    plt.legend()
    plt.grid(True)
    plt.show()

In [ ]:
def param_tuning(param_grid, nombre_prueba):
    earlystopping = callbacks.EarlyStopping(monitor = "val_loss",
                                        mode = "min",
                                        patience = 5,
                                        restore_best_weights = True)
    
    mod_hist = []
    for params in param_grid:
        models = []
        modelo = train_model(params, X_train, y_train, X_test, y_test, nombre_prueba, earlystopping)
        models.append(modelo['model'])
        models.append(modelo['history'])
        mod_hist.append(models)
    
    return mod_hist

### Prueba de thresold

In [ ]:
param_grid = {
    'act_func': ['relu'],
    'batch_size': [32],
    'epochs': [100],
    'optimizer': ['adam'],
    'learning_rate': [0.001],
    'layers': [2],
    'hidden_units': [64],
    'threshold': [0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.75, 0.8],
}

In [ ]:
params = ParameterGrid(param_grid)

In [ ]:
models = param_tuning(params, 'binary_balanced_threshold')

#### Según los modelos creados, los que tienen mejor F1_score son los modelos con un umbral del 0.65 y 0.7

In [ ]:
param_grid = {
    'act_func': ['relu', 'tanh', 'selu', 'sigmoid'],
    'batch_size': [32],
    'epochs': [100],
    'optimizer': ['adam'],
    'learning_rate': [0.001],
    'layers': [2],
    'hidden_units': [64],
    'threshold': [0.65, 0.7]
    }

In [ ]:
params = ParameterGrid(param_grid)

In [ ]:
models = param_tuning(params, 'binary_balanced_act_func')

#### Según los modelos creados, la mejor función de activación es relu. Con un threshold de 0.7 o 0.65

In [ ]:
param_grid = {
    'act_func': ['relu'],
    'batch_size': [32],
    'epochs': [100],
    'optimizer': ['adam'],
    'learning_rate': [0.001],
    'layers': [2, 3, 4],
    'hidden_units': [32, 64, 128, 256],
    'threshold': [0.65, 0.7]
    }

In [ ]:
params = ParameterGrid(param_grid)

In [ ]:
models = param_tuning(params, 'binary_balanced_layers&units')

#### Según los modelos creados, la mejor combinación de capas de unidades ocultas es, 3 capas densas de 128 capas ocultas cada una

In [ ]:
param_grid = {
    'act_func': ['relu'],
    'batch_size': [32],
    'epochs': [100],
    'optimizer': ['adam', 'adagrad', 'sgd'],
    'learning_rate': [0.0001, 0.001, 0.01, 0.1],
    'layers': [3],
    'hidden_units': [128],
    'threshold': [0.7]
    }

In [ ]:
params = ParameterGrid(param_grid)

In [ ]:
models = param_tuning(params, 'binary_balanced_opt&lr')

In [ ]:
param_grid = {
    'act_func': ['relu'],
    'batch_size': [8, 16, 32, 64, 128],
    'epochs': [100],
    'optimizer': ['adagrad'],
    'learning_rate': [0.0001],
    'layers': [3],
    'hidden_units': [128],
    'threshold': [0.7]
    }

#### De los modelos creados, el que tiene un mejor desempeño en la comparación entre entrenamiento y validación es Adagrad con una tasa de aprendizaje de 0.0001

In [ ]:
params = ParameterGrid(param_grid)

In [ ]:
models = param_tuning(params, 'binary_balanced_batch_size')

In [ ]:
for mod, hist in models:
    plt.plot(hist.history['loss'], label='Entrenamiento')
    plt.plot(hist.history['val_loss'], label='Validación')
    plt.xlabel('Época')
    plt.ylabel('Pérdida')
    plt.legend()
    plt.grid(True)
    plt.show()