# Fuentes de modelización

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Limpieza de los datos

### Carga de los datos después de la limpieza

In [2]:
datos_limpios = pd.read_csv('/Users/melo/Downloads/model_data.csv')
datos_limpios

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,estu_yearnacimiento
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,No,No,No,A2,332,2000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Ninguno,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,2001.0
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0

### Creación de las categorías del desempeño en el icfes según percentiles

In [3]:
# datos_limpios['desemp'] = pd.qcut(datos_limpios['punt_global'], q=5, labels=['Bajo', 'Medio bajo', 'Medio', 'Medio alto', 'Alto'])
# datos_limpios

In [4]:
datos_limpios['Ingresa'] = np.where(datos_limpios['punt_global'] >= 300, 1, 0)
datos_limpios

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,estu_yearnacimiento,Ingresa
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0,0
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0,0
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0,0
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0,0
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Estrato 2,3 a 4,No,No,No,No,A2,332,2000.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,2001.0,0
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0,0
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0,0
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0,0
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0,0

### Transformación de los datos del año de nacimiento a la edad del candidato

In [5]:
datos_limpios['estu_edad'] = 2019 - datos_limpios['estu_yearnacimiento']
datos_limpios = datos_limpios.drop(columns=['estu_yearnacimiento'])
datos_limpios

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,Ingresa,estu_edad
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.0
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.0
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.0
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.0
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Estrato 2,3 a 4,No,No,No,No,A2,332,1,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,0,18.0
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.0
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.0
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.0
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.0

In [6]:
pd.set_option('display.float_format', '{:.2f}'.format)
datos_limpios.describe()

       punt_global    Ingresa  estu_edad
count   1027084.00 1027084.00 1027076.00
mean        247.87       0.17      17.76
std          51.04       0.38       3.55
min           0.00       0.00       0.00
25%         209.00       0.00      17.00
50%         245.00       0.00      17.00
75%         284.00       0.00      18.00
max         477.00       1.00     119.00

### Eliminación de outliers (presentan el examen personas entre 15 y 40 años)

In [7]:
datos_filtrados = datos_limpios[(datos_limpios['estu_edad'] >= 15) & (datos_limpios['estu_edad'] <= 40)]
datos_filtrados

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,Ingresa,estu_edad
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.00
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.00
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.00
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.00
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Estrato 2,3 a 4,No,No,No,No,A2,332,1,19.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,0,18.00
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.00
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.00
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.00
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.00

In [8]:
datos_filtrados.describe()

       punt_global    Ingresa  estu_edad
count   1020784.00 1020784.00 1020784.00
mean        248.13       0.17      17.61
std          50.97       0.38       2.22
min           0.00       0.00      15.00
25%         210.00       0.00      17.00
50%         245.00       0.00      17.00
75%         284.00       0.00      18.00
max         477.00       1.00      40.00

In [9]:
datos_filtrados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020784 entries, 0 to 1027083
Data columns (total 23 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   estu_tipodocumento    1020784 non-null  object
 1   cole_area_ubicacion   1020784 non-null  object
 2   cole_bilingue         1020784 non-null  object
 3   cole_calendario       1020784 non-null  object
 4   cole_caracter         1020784 non-null  object
 5   cole_genero           1020784 non-null  object
 6   cole_jornada          1020784 non-null  object
 7   cole_naturaleza       1020784 non-null  object
 8   estu_depto_reside     1020784 non-null  object
 9   estu_genero           1020784 non-null  object
 10  fami_cuartoshogar     1020784 non-null  object
 11  fami_educacionmadre   1020784 non-null  object
 12  fami_educacionpadre   1020784 non-null  object
 13  fami_estratovivienda  1020784 non-null  object
 14  fami_personashogar    1020784 non-null  object
 15  fami_tieneautomovil   1020784 non-null  object
 16  fami_tienecomputador  1020784 non-null  object
 17  fami_tieneinternet    1020784 non-null  object
 18  fami_tienelavadora    1020784 non-null  object
 19  desemp_ingles         1020784 non-null  object
 20  punt_global           1020784 non-null  int64
 21  Ingresa               1020784 non-null  int64
 22  estu_edad             1020784 non-null  float64
dtypes: float64(1), int64(2), object(20)
memory usage: 186.9+ MB

## Selección de variables

### Separación de variables en numéricas y categóricas (las categóricas se separan en tres grupos: cole, estu, fami)

In [10]:
var_cat = datos_limpios.select_dtypes(include=['object']).columns
var_cat_cole = [col for col in var_cat if col.startswith('cole')]
var_cat_estu = [col for col in var_cat if col.startswith('estu')]
var_cat_estu.append('desemp_ingles')
var_cat_fami = [col for col in var_cat if col.startswith('fami')]
var_num = 'estu_edad'
target = 'punt_global'

In [11]:
for col in var_cat:
    print(datos_filtrados[col].value_counts())

estu_tipodocumento
TI     852248
CC     161896
CR       2962
CE       2004
NES      1006
PEP       428
PE        172
RC         38
V          14
CCB         8
PC          8
Name: count, dtype: int64
cole_area_ubicacion
URBANO    862338
RURAL     158446
Name: count, dtype: int64
cole_bilingue
N           849330
Faltante    161282
S            10172
Name: count, dtype: int64
cole_calendario
A       1013406
OTRO       5390
B          1988
Name: count, dtype: int64
cole_caracter
ACADÉMICO            557152
TÉCNICO/ACADÉMICO    340630
TÉCNICO              110026
NO APLICA             12976
Name: count, dtype: int64
cole_genero
MIXTO        987182
FEMENINO      26052
MASCULINO      7550
Name: count, dtype: int64
cole_jornada
MAÑANA      486560
COMPLETA    171900
UNICA       128200
TARDE       111998
SABATINA     64976
NOCHE        57150
Name: count, dtype: int64
cole_naturaleza
OFICIAL       779258
NO OFICIAL    241526
Name: count, dtype: int64
estu_depto_reside
BOGOTÁ             159854
ANTIOQUIA          138582
VALLE               72446
CUNDINAMARCA        68190
ATLANTICO           59670
SANTANDER           47910
BOLIVAR             45746
CORDOBA             37804
BOYACA              31946
TOLIMA              30892
NARIÑO              30672
MAGDALENA           30476
NORTE SANTANDER     30190
HUILA               26212
CAUCA               25192
CESAR               24614
META                23376
SUCRE               20284
RISARALDA           20218
CALDAS              19746
LA GUAJIRA          15940
QUINDIO             11814
CASANARE            11288
CHOCO                8764
CAQUETA              8622
PUTUMAYO             7262
ARAUCA               6388
GUAVIARE             1874
AMAZONAS             1402
SAN ANDRES           1190
VICHADA               932
VAUPES                558
GUAINIA               490
EXTRANJERO            240
Name: count, dtype: int64
estu_genero
F    553090
M    467694
Name: count, dtype: int64
fami_cuartoshogar
Tres          412164
Dos           358882
Cuatro        133978
Uno            52276
Cinco          41342
Seis o mas     22142
Name: count, dtype: int64
fami_educacionmadre
Secundaria (Bachillerato) completa      272116
Primaria incompleta                     157038
Secundaria (Bachillerato) incompleta    151104
Educación profesional completa          107930
Técnica o tecnológica completa          105286
Primaria completa                       105140
Técnica o tecnológica incompleta         31628
Educación profesional incompleta         24602
Ninguno                                  24218
Postgrado                                21468
No sabe                                  18164
No Aplica                                 2090
Name: count, dtype: int64
fami_educacionpadre
Secundaria (Bachillerato) completa      235928
Primaria incompleta                     199176
Secundaria (Bachillerato) incompleta    141040
Primaria completa                       106636
Educación profesional completa           91860
Técnica o tecnológica completa           70272
No sabe                                  63432
Ninguno                                  38420
Técnica o tecnológica incompleta         21646
Educación profesional incompleta         20106
Postgrado                                18732
No Aplica                                13536
Name: count, dtype: int64
fami_estratovivienda
Estrato 2    409802
Estrato 1    319354
Estrato 3    216848
Estrato 4     51430
Estrato 5     15970
Estrato 6      7380
Name: count, dtype: int64
fami_personashogar
3 a 4      506636
5 a 6      322610
7 a 8       84230
1 a 2       74506
9 o más     32802
Name: count, dtype: int64
fami_tieneautomovil
No    777336
Si    243448
Name: count, dtype: int64
fami_tienecomputador
Si    581910
No    438874
Name: count, dtype: int64
fami_tieneinternet
Si    624932
No    395852
Name: count, dtype: int64
fami_tienelavadora
Si    789150
No    231634
Name: count, dtype: int64
desemp_ingles
A-    492006
A1    293300
A2    153584
B1     67588
B+     14306
Name: count, dtype: int64

In [13]:
datos_finales = datos_filtrados.copy()
datos_finales['estu_tipodocumento'] = datos_filtrados['estu_tipodocumento'].apply(
    lambda x: x if x in ['CC', 'TI'] else 'Otro'
)

### Scatter plot para ver la relación entre la edad y el puntaje global

In [ ]:
plt.scatter(datos_finales[var_num], datos_filtrados[target])
plt.xlabel(var_num)

### Boxplots entre las variables categóricas del colegio con el puntaje global

In [ ]:
for col in var_cat_cole:
    plt.figure(figsize=(10, 6))
    
    sns.boxplot(data=datos_finales, x=col, y=target)
    
    plt.title(f'{target} por {col}')
    plt.xlabel(col)
    plt.ylabel(target)
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.tight_layout()
    
    plt.show()

#### Usamos las variables más relevantes para la variable de interés (punt_global en este caso que después es desemp)
#### cole_area_ubicacion
#### cole_calendario
#### cole_genero
#### cole_jornada
#### cole_naturaleza

### Boxplots entre las variables categóricas del estudiante con el puntaje global

In [ ]:
for col in var_cat_estu:
    plt.figure(figsize=(10, 6))
    
    sns.boxplot(data=datos_finales, x=col, y=target)
    
    plt.title(f'{target} por {col}')
    plt.xlabel(col)
    plt.ylabel(target)
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.tight_layout()
    
    plt.show()

#### Usamos las variables más relevantes para la variable de interés (punt_global en este caso que después es desemp)
#### estu_tipodocumento
#### estu_depto_reside
#### estu_genero
#### desemp_ingles

### Boxplots entre las variables categóricas de la familia con el puntaje global

In [ ]:
for col in var_cat_fami:
    plt.figure(figsize=(10, 6))
    
    sns.boxplot(data=datos_finales, x=col, y=target)
    
    plt.title(f'{target} por {col}')
    plt.xlabel(col)
    plt.ylabel(target)
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.tight_layout()
    
    plt.show()

#### Usamos las variables más relevantes para la variable de interés (punt_global en este caso que después es desemp)
#### fami_cuartohogar
#### fami_personashogar
#### fami_educacionmadre
#### fami_educacionpadre
#### fami_estratovivienda
#### fami_tieneautomovil
#### fami_tienecomputador
#### fami_tieneinternet
#### fami_tienelavadora

In [14]:
datos_modelo = datos_finales.copy()
datos_modelo = datos_modelo.drop(columns=['cole_bilingue', 'cole_caracter', 'punt_global'])
datos_modelo

,estu_tipodocumento,cole_area_ubicacion,cole_calendario,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,Ingresa,estu_edad
0,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,19.00
1,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,19.00
2,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,19.00
3,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,19.00
4,CC,URBANO,A,MIXTO,UNICA,OFICIAL,VALLE,F,Dos,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,No,No,No,A2,1,19.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,A,MIXTO,SABATINA,OFICIAL,TOLIMA,F,Tres,Primaria incompleta,Ninguno,Estrato 2,5 a 6,No,Si,Si,Si,A-,0,18.00
1027080,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,17.00
1027081,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,17.00
1027082,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,19.00
1027083,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,19.00

## Fuentes de modelización

In [15]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.model_selection import ParameterGrid, ParameterSampler
import mlflow
import keras
from keras import callbacks

In [16]:
# Instanciar el scaler
scaler = StandardScaler()

# Escalar solo col1 y col2
datos_modelo['estu_edad'] = scaler.fit_transform(datos_modelo[['estu_edad']])
datos_modelo

,estu_tipodocumento,cole_area_ubicacion,cole_calendario,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,Ingresa,estu_edad
0,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,0.63
1,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,0.63
2,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,0.63
3,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,0.63
4,CC,URBANO,A,MIXTO,UNICA,OFICIAL,VALLE,F,Dos,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,No,No,No,A2,1,0.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,A,MIXTO,SABATINA,OFICIAL,TOLIMA,F,Tres,Primaria incompleta,Ninguno,Estrato 2,5 a 6,No,Si,Si,Si,A-,0,0.18
1027080,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,-0.27
1027081,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,-0.27
1027082,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,0.63
1027083,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,0.63

In [17]:
y = datos_modelo['Ingresa']
datos_X = datos_modelo.drop(columns=['Ingresa'])

In [18]:
X = pd.get_dummies(datos_X, drop_first = False, dtype = int)
X

,estu_edad,estu_tipodocumento_CC,estu_tipodocumento_Otro,estu_tipodocumento_TI,cole_area_ubicacion_RURAL,cole_area_ubicacion_URBANO,cole_calendario_A,cole_calendario_B,cole_calendario_OTRO,cole_genero_FEMENINO,...,fami_tienecomputador_Si,fami_tieneinternet_No,fami_tieneinternet_Si,fami_tienelavadora_No,fami_tienelavadora_Si,desemp_ingles_A-,desemp_ingles_A1,desemp_ingles_A2,desemp_ingles_B+,desemp_ingles_B1
0,0.63,1,0,0,0,1,1,0,0,0,...,1,0,1,0,1,0,1,0,0,0
1,0.63,1,0,0,0,1,1,0,0,0,...,1,0,1,0,1,0,1,0,0,0
2,0.63,0,0,1,0,1,1,0,0,0,...,1,0,1,0,1,0,1,0,0,0
3,0.63,0,0,1,0,1,1,0,0,0,...,1,0,1,0,1,0,1,0,0,0
4,0.63,1,0,0,0,1,1,0,0,0,...,0,1,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,0.18,0,0,1,0,1,1,0,0,0,...,1,0,1,0,1,1,0,0,0,0
1027080,-0.27,0,0,1,0,1,1,0,0,0,...,0,1,0,1,0,1,0,0,0,0
1027081,-0.27,0,0,1,0,1,1,0,0,0,...,0,1,0,1,0,1,0,0,0,0
1027082,0.63,1,0,0,0,1,1,0,0,0,...,1,0,1,0,1,0,0,1,0,0
1027083,0.63,1,0,0,0,1,1,0,0,0,...,1,0,1,0,1,0,0,1,0,0

In [ ]:
y = datos_modelo2[['desemp_Bajo', 'desemp_Medio', 'desemp_Alto']]
X = datos_modelo2.drop(['desemp_Bajo', 'desemp_Medio', 'desemp_Alto'], axis=1)
X

In [19]:
y

0          0
1          0
2          0
3          0
4          1
          ..
1027079    0
1027080    0
1027081    0
1027082    0
1027083    0
Name: Ingresa, Length: 1020784, dtype: int64

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [36]:
def train_model(parameters, train_X, train_y, test_X, test_y, experiment_name, early_stop):
    
    model = Sequential()
    model.add(Input(shape=(train_X.shape[1],)))
    model.add(Dense(parameters['hidden_units'], activation = parameters['act_func']))
    
    if parameters['layers'] > 1:
        model.add(Dense(parameters['hidden_units'], activation = parameters['act_func']))
    if parameters['layers'] == 3:
        model.add(Dense(parameters['hidden_units'], activation = parameters['act_func']))
        
    model.add(Dense(1, activation='sigmoid'))
    
    if parameters['optimizer'] == 'adam':
        opt = keras.optimizers.Adam(learning_rate = parameters['learning_rate'])
    elif parameters['optimizer'] == 'adagrad':
        opt = keras.optimizers.Adagrad(learning_rate = parameters['learning_rate'])
    elif parameters['optimizer'] == 'sgd':
        opt = keras.optimizers.SGD(learning_rate = parameters['learning_rate'])
    
    model.compile(optimizer = opt, loss = 'binary_crossentropy', metrics = ['accuracy', 'true_positives', 'true_negatives', 'false_positives', 'false_negatives'])
    
    # defina el servidor para llevar el registro de modelos y artefactos
    mlflow.set_tracking_uri('http://127.0.0.1:5000')
    # registre el experimento
    experiment = mlflow.set_experiment(experiment_name)
    
    # Aquí se ejecuta MLflow sin especificar un nombre o id del experimento. MLflow los crea un experimento para este cuaderno por defecto y guarda las características del experimento y las métricas definidas. 
    # Para ver el resultado de las corridas haga click en Experimentos en el menú izquierdo. 
    with mlflow.start_run(experiment_id=experiment.experiment_id):
        
        history = model.fit(train_X, train_y,
                  epochs = parameters['epochs'],
                  batch_size = parameters['batch_size'],
                  validation_split = 0.2,
                  callbacks = [early_stop],
                  verbose = 0
                  )
        
        #Evaluar el modelo
        eval_model = model.evaluate(test_X, test_y, verbose = 0)
        loss = eval_model[0]
        accuracy = eval_model[1]
        tp = eval_model[2]
        tn = eval_model[3]
        fp = eval_model[4]
        fn = eval_model[5]
        
        pos_precision = tp / (tp + fp)
        neg_precision = tn / (tn + fn)
        pos_recall = tp / (tp + fn)
        neg_recall = tn / (tn + fp)
        error_I = fp / (fp + tn)
        error_II = fn / (fn + tp)
        
        # Log parameters and results
        mlflow.log_params(parameters)
        mlflow.log_metric("accuracy", round(accuracy, 5))
        mlflow.log_metric("test_loss", round(loss, 5))
        mlflow.log_metric("positive_precision", round(pos_precision, 5))
        mlflow.log_metric("negative_precision", round(neg_precision, 5))
        mlflow.log_metric("positive_recall", round(pos_recall, 5))
        mlflow.log_metric("negative_recall", round(neg_recall, 5))
        mlflow.log_metric("Error_I", round(error_I, 5))
        mlflow.log_metric("Error_II", round(error_II, 5))
        print(f'Loss: {loss}, Accuracy: {accuracy}')
        
        
        
        # cm = confusion_matrix(y_test, y_pred)
        # pre_bajo = cm[0, 0] / (cm[0, 0] + cm[1, 0] + cm[2, 0])
        # pre_medio = cm[1, 1] / (cm[0, 1] + cm[1, 1] + cm[2, 1])
        # pre_alto = cm[2, 2] / (cm[0, 2] + cm[1, 2] + cm[2, 2])
        # rec_bajo = cm[0, 0] / (cm[0, 0] + cm[0, 1] + cm[0, 2])
        # rec_medio = cm[1, 1] / (cm[1, 0] + cm[1, 1] + cm[1, 2])
        # rec_alto = cm[2, 2] / (cm[2, 0] + cm[2, 1] + cm[2, 2])
        # tot_bajo = cm[0, 0] + cm[0, 1] + cm[0, 2]
        # tot_medio = cm[1, 0] + cm[1, 1] + cm[1, 2]
        # tot_alto = cm[2, 0] + cm[2, 1] + cm[2, 2]
        # tot = tot_bajo + tot_medio + tot_alto
        # wa_pre = ((tot_bajo * pre_bajo) + (tot_medio * pre_medio) + (tot_alto * pre_alto)) / tot
        # wa_rec = ((tot_bajo * rec_bajo) + (tot_medio * rec_medio) + (tot_alto * rec_alto)) / tot
        
        
        # mlflow.log_metric("precision_bajo", round(pre_bajo, 5))
        # mlflow.log_metric("precision_medio", round(pre_medio, 5))
        # mlflow.log_metric("precision_alto", round(pre_alto, 5))
        # mlflow.log_metric("recall_bajo", round(rec_bajo, 5))
        # mlflow.log_metric("recall_medio", round(rec_medio, 5))
        # mlflow.log_metric("recall_alto", round(rec_alto, 5))
        # mlflow.log_metric("weighted_precision", round(wa_pre, 5))
        # mlflow.log_metric("weighted_recall", round(wa_rec, 5))
        
        # Log model
        mlflow.tensorflow.log_model(model, "model")
            
    
        return {"model": model, 'history' : history}

In [37]:
def show_history(history):
    plt.plot(hist.history['loss'], label='Entrenamiento')
    plt.plot(hist.history['val_loss'], label='Validación')
    plt.xlabel('Época')
    plt.ylabel('Precisión')
    plt.legend()
    plt.grid(True)
    plt.show()

In [38]:
def param_tuning(param_grid, nombre_prueba):
    earlystopping = callbacks.EarlyStopping(monitor = "val_loss",
                                        mode = "min",
                                        patience = 5,
                                        restore_best_weights = True)
    
    mod_hist = []
    for params in param_grid:
        models = []
        modelo = train_model(params, X_train, y_train, X_test, y_test, nombre_prueba, earlystopping)
        models.append(modelo['model'])
        models.append(modelo['history'])
        mod_hist.append(models)
    
    return mod_hist

In [ ]:
grid = {
    'act_func': ['relu'],
    'batch_size': [32],
    'epochs': [100],
    'optimizer': ['adam'],
    'learning_rate': [0.001],
    'layers': [1, 2, 3],
    'hidden_units': [8, 16, 32, 64, 128]
}
parameters_grid = ParameterGrid(grid)

In [ ]:
models_layer_units = param_tuning(parameters_grid, 'layers&hidden_units')

In [39]:
param_grid = {
    'act_func': ['relu', 'tanh', 'sigmoid', 'selu'],
    'batch_size': [32, 64, 128],
    'epochs': [10, 30, 50, 100],
    'optimizer': ['adam', 'adagrad', 'sgd'],
    'learning_rate': [0.0001, 0.001, 0.01, 0.1],
    'layers': [2, 3],
    'hidden_units': [64, 128, 256]
}

In [40]:
n_iter = 20  # número de combinaciones a probar
random_params = ParameterSampler(param_grid, n_iter=n_iter)

In [41]:
models_layer_units = param_tuning(random_params, 'binary_prueba2_random')

2025/05/20 20:03:49 INFO mlflow.tracking.fluent: Experiment with name 'binary_prueba2_random' does not exist. Creating a new experiment.
2025/05/20 20:23:31 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.2509140968322754, Accuracy: 0.8892812728881836

2025/05/20 20:23:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run powerful-kite-451 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/7fc38c2e49284e068597cff61d8feacb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:25:42 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.2500515580177307, Accuracy: 0.8903049826622009

2025/05/20 20:25:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run thundering-midge-323 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/818754440b1e487681fcdaa7c3543425
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:33:03 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.24783341586589813, Accuracy: 0.8915442824363708

2025/05/20 20:33:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run serious-penguin-79 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/7a77e34133f941678ae6da2f5b093ad5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:35:48 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.24899062514305115, Accuracy: 0.890378475189209

2025/05/20 20:35:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run delicate-cow-689 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/bf7e27f68fed4c4e80de776f5ff7068a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:37:29 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.25002941489219666, Accuracy: 0.8898397088050842

2025/05/20 20:37:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run youthful-bird-494 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/fa5216ca03e74c5dab8614d30631b43f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:38:08 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.2493741363286972, Accuracy: 0.8904372453689575

2025/05/20 20:38:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run serious-bass-358 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/4ca7e37aeb294c34ad804a5d1c054cd2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:44:31 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.2498447746038437, Accuracy: 0.8906087279319763

2025/05/20 20:44:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run dashing-sloth-382 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/fafcb35579904f25acc8c5aa0add69ec
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:47:55 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.24960626661777496, Accuracy: 0.8898886442184448

2025/05/20 20:47:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run crawling-crab-121 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/2abffb9e96384ab5b7cb8b9369ed9d4b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:49:09 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.2518466114997864, Accuracy: 0.8894674181938171

2025/05/20 20:49:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run nervous-boar-939 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/427872927412490098a52ae6eb0bf631
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:51:03 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.2490321844816208, Accuracy: 0.8906723856925964

2025/05/20 20:51:07 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run luxuriant-hog-104 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/7c628a18205649b480a5ff766503dd9a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:54:08 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.24945075809955597, Accuracy: 0.8906087279319763

2025/05/20 20:54:13 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run omniscient-crab-228 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/199cc0215bd6402389d2a172dd614061
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:54:48 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.249928817152977, Accuracy: 0.8902755975723267

2025/05/20 20:54:52 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run legendary-quail-263 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/c6ad0b0047fc4c038c95971390cff2f7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 20:56:01 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.25004205107688904, Accuracy: 0.8895360231399536

2025/05/20 20:56:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run adorable-mink-158 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/d0200e91c7c84b7599b96633718821f1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 21:00:52 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.253021776676178, Accuracy: 0.8893008828163147

2025/05/20 21:00:57 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run able-mole-3 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/be983017e4b84816af9990d3064c0c38
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 21:05:48 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.2532568871974945, Accuracy: 0.8892322778701782

2025/05/20 21:05:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run treasured-robin-262 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/d6afd6411cd645edb30edf2f8b2b7953
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 21:06:46 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.26292145252227783, Accuracy: 0.8882673382759094

2025/05/20 21:06:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run languid-trout-975 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/2bf542f95e2145d58e58cdf98fc82f2f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 21:07:31 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.2504141330718994, Accuracy: 0.8896339535713196

2025/05/20 21:07:35 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run caring-fly-233 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/e24f1802d1c4492895275172baaf4434
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 21:32:38 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.25376468896865845, Accuracy: 0.8883359432220459

2025/05/20 21:32:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run popular-horse-828 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/6336e91d705c4f699a1a0b1d8124310d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 21:33:54 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.25200504064559937, Accuracy: 0.8893449902534485

2025/05/20 21:33:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run placid-shrew-519 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/1e3957a606c640bcb5e5ee3d9ef99324
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

2025/05/20 21:50:19 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.2512875497341156, Accuracy: 0.8903049826622009

2025/05/20 21:50:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run mercurial-wolf-932 at: http://127.0.0.1:5000/#/experiments/897762295914497557/runs/b9a2b8bb5bff49789c169f0a5a3016b9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/897762295914497557

### Prueba de modelos con dos capas y cambiando el número de neuronas y funciones de activación por capa

In [ ]:
def train_model(parameters, train_X, train_y, test_X, test_y, experiment_name, early_stop):
    
    model = Sequential()
    model.add(Input(shape=(train_X.shape[1],)))
    model.add(Dense(parameters['hidden_units_1'], activation = parameters['act_func_1']))
    model.add(Dense(parameters['hidden_units_2'], activation = parameters['act_func_2']))
        
    model.add(Dense(3, activation='softmax'))
    
    if parameters['optimizer'] == 'adam':
        opt = keras.optimizers.Adam(learning_rate = parameters['learning_rate'])
    elif parameters['optimizer'] == 'adagrad':
        opt = keras.optimizers.Adagrad(learning_rate = parameters['learning_rate'])
    elif parameters['optimizer'] == 'sgd':
        opt = keras.optimizers.SGD(learning_rate = parameters['learning_rate'])
    
    model.compile(optimizer = opt, loss = 'categorical_crossentropy', metrics = ['accuracy'])
    
    # defina el servidor para llevar el registro de modelos y artefactos
    mlflow.set_tracking_uri('http://127.0.0.1:5000')
    # registre el experimento
    experiment = mlflow.set_experiment(experiment_name)
    
    # Aquí se ejecuta MLflow sin especificar un nombre o id del experimento. MLflow los crea un experimento para este cuaderno por defecto y guarda las características del experimento y las métricas definidas. 
    # Para ver el resultado de las corridas haga click en Experimentos en el menú izquierdo. 
    with mlflow.start_run(experiment_id=experiment.experiment_id):
        
        history = model.fit(train_X, train_y,
                  epochs = parameters['epochs'],
                  batch_size = parameters['batch_size'],
                  validation_split = 0.2,
                  callbacks = [early_stop],
                  verbose = 0
                  )
        
        #Evaluar el modelo
        eval_model = model.evaluate(test_X, test_y, verbose = 0)
        loss = eval_model[0]
        accuracy = eval_model[1]
        # Log parameters and results
        mlflow.log_params(parameters)
        mlflow.log_metric("accuracy", round(accuracy, 5))
        mlflow.log_metric("test_loss", round(loss, 5))
        print(f'Loss: {loss}, Accuracy: {accuracy}')
        
        #Valores de predicción (Precision & Recall)
        y_pred = model.predict(test_X)
        y_pred = np.argmax(y_pred, axis=1)
        y_test = np.argmax(test_y, axis=1)
        
        cm = confusion_matrix(y_test, y_pred)
        pre_bajo = cm[0, 0] / (cm[0, 0] + cm[1, 0] + cm[2, 0])
        pre_medio = cm[1, 1] / (cm[0, 1] + cm[1, 1] + cm[2, 1])
        pre_alto = cm[2, 2] / (cm[0, 2] + cm[1, 2] + cm[2, 2])
        rec_bajo = cm[0, 0] / (cm[0, 0] + cm[0, 1] + cm[0, 2])
        rec_medio = cm[1, 1] / (cm[1, 0] + cm[1, 1] + cm[1, 2])
        rec_alto = cm[2, 2] / (cm[2, 0] + cm[2, 1] + cm[2, 2])
        tot_bajo = cm[0, 0] + cm[0, 1] + cm[0, 2]
        tot_medio = cm[1, 0] + cm[1, 1] + cm[1, 2]
        tot_alto = cm[2, 0] + cm[2, 1] + cm[2, 2]
        tot = tot_bajo + tot_medio + tot_alto
        wa_pre = ((tot_bajo * pre_bajo) + (tot_medio * pre_medio) + (tot_alto * pre_alto)) / tot
        wa_rec = ((tot_bajo * rec_bajo) + (tot_medio * rec_medio) + (tot_alto * rec_alto)) / tot
        
        
        mlflow.log_metric("precision_bajo", round(pre_bajo, 5))
        mlflow.log_metric("precision_medio", round(pre_medio, 5))
        mlflow.log_metric("precision_alto", round(pre_alto, 5))
        mlflow.log_metric("recall_bajo", round(rec_bajo, 5))
        mlflow.log_metric("recall_medio", round(rec_medio, 5))
        mlflow.log_metric("recall_alto", round(rec_alto, 5))
        mlflow.log_metric("weighted_precision", round(wa_pre, 5))
        mlflow.log_metric("weighted_recall", round(wa_rec, 5))
        
        # Log model
        mlflow.tensorflow.log_model(model, "model")
            
    
        return {"model": model, 'history' : history}

In [ ]:
param_grid = {
    'act_func_1': ['relu', 'tanh', 'selu'],
    'act_func_2': ['relu', 'tanh', 'selu'],
    'batch_size': [32],
    'epochs': [50],
    'optimizer': ['adagrad'],
    'learning_rate': [0.001],
    'hidden_units_1': [64, 128],
    'hidden_units_2': [64, 128],
}

parameters_grid = ParameterGrid(param_grid)

In [ ]:
models_layer_units = param_tuning(parameters_grid, 'neuronas_funciones')