# Fuentes de modelización

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Limpieza de los datos

### Carga de los datos después de la limpieza

In [2]:
datos_limpios = pd.read_csv('/Users/melo/Downloads/model_data.csv')
datos_limpios

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,estu_yearnacimiento
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,No,No,No,A2,332,2000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Ninguno,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,2001.0
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0

### Creación de las categorías del desempeño en el icfes según percentiles

In [3]:
datos_limpios['Ingresa'] = np.where(datos_limpios['punt_global'] >= 300, 1, 0)
datos_limpios

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,estu_yearnacimiento,Ingresa
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0,0
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,2000.0,0
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0,0
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,2000.0,0
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Estrato 2,3 a 4,No,No,No,No,A2,332,2000.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,2001.0,0
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0,0
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,2002.0,0
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0,0
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,2000.0,0

### Transformación de los datos del año de nacimiento a la edad del candidato

In [4]:
datos_limpios['estu_edad'] = 2019 - datos_limpios['estu_yearnacimiento']
datos_limpios = datos_limpios.drop(columns=['estu_yearnacimiento'])
datos_limpios

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,Ingresa,estu_edad
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.0
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.0
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.0
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.0
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Estrato 2,3 a 4,No,No,No,No,A2,332,1,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,0,18.0
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.0
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.0
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.0
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.0

In [5]:
pd.set_option('display.float_format', '{:.2f}'.format)
datos_limpios.describe()

       punt_global    Ingresa  estu_edad
count   1027084.00 1027084.00 1027076.00
mean        247.87       0.17      17.76
std          51.04       0.38       3.55
min           0.00       0.00       0.00
25%         209.00       0.00      17.00
50%         245.00       0.00      17.00
75%         284.00       0.00      18.00
max         477.00       1.00     119.00

### Eliminación de outliers (presentan el examen personas entre 15 y 40 años)

In [6]:
datos_filtrados = datos_limpios[(datos_limpios['estu_edad'] >= 15) & (datos_limpios['estu_edad'] <= 40)]
datos_filtrados

,estu_tipodocumento,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,...,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_global,Ingresa,estu_edad
0,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.00
1,CC,URBANO,N,A,ACADÉMICO,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,...,Estrato 2,1 a 2,Si,Si,Si,Si,A1,260,0,19.00
2,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.00
3,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,...,Estrato 1,7 a 8,No,Si,Si,Si,A1,253,0,19.00
4,CC,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,VALLE,F,...,Estrato 2,3 a 4,No,No,No,No,A2,332,1,19.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,SABATINA,OFICIAL,TOLIMA,F,...,Estrato 2,5 a 6,No,Si,Si,Si,A-,141,0,18.00
1027080,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.00
1027081,TI,URBANO,N,A,TÉCNICO/ACADÉMICO,MIXTO,UNICA,OFICIAL,CALDAS,F,...,Estrato 2,3 a 4,No,No,No,No,A-,181,0,17.00
1027082,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.00
1027083,CC,URBANO,N,A,ACADÉMICO,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,...,Estrato 3,3 a 4,Si,Si,Si,Si,A2,235,0,19.00

In [7]:
datos_filtrados.describe()

       punt_global    Ingresa  estu_edad
count   1020784.00 1020784.00 1020784.00
mean        248.13       0.17      17.61
std          50.97       0.38       2.22
min           0.00       0.00      15.00
25%         210.00       0.00      17.00
50%         245.00       0.00      17.00
75%         284.00       0.00      18.00
max         477.00       1.00      40.00

In [8]:
datos_filtrados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020784 entries, 0 to 1027083
Data columns (total 23 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   estu_tipodocumento    1020784 non-null  object
 1   cole_area_ubicacion   1020784 non-null  object
 2   cole_bilingue         1020784 non-null  object
 3   cole_calendario       1020784 non-null  object
 4   cole_caracter         1020784 non-null  object
 5   cole_genero           1020784 non-null  object
 6   cole_jornada          1020784 non-null  object
 7   cole_naturaleza       1020784 non-null  object
 8   estu_depto_reside     1020784 non-null  object
 9   estu_genero           1020784 non-null  object
 10  fami_cuartoshogar     1020784 non-null  object
 11  fami_educacionmadre   1020784 non-null  object
 12  fami_educacionpadre   1020784 non-null  object
 13  fami_estratovivienda  1020784 non-null  object
 14  fami_personashogar    1020784 non-null  object
 15  fami_tieneautomovil   1020784 non-null  object
 16  fami_tienecomputador  1020784 non-null  object
 17  fami_tieneinternet    1020784 non-null  object
 18  fami_tienelavadora    1020784 non-null  object
 19  desemp_ingles         1020784 non-null  object
 20  punt_global           1020784 non-null  int64
 21  Ingresa               1020784 non-null  int64
 22  estu_edad             1020784 non-null  float64
dtypes: float64(1), int64(2), object(20)
memory usage: 186.9+ MB

## Selección de variables

### Separación de variables en numéricas y categóricas (las categóricas se separan en tres grupos: cole, estu, fami)

In [9]:
var_cat = datos_limpios.select_dtypes(include=['object']).columns
var_cat_cole = [col for col in var_cat if col.startswith('cole')]
var_cat_estu = [col for col in var_cat if col.startswith('estu')]
var_cat_estu.append('desemp_ingles')
var_cat_fami = [col for col in var_cat if col.startswith('fami')]
var_num = 'estu_edad'
target = 'punt_global'

In [10]:
for col in var_cat:
    print(datos_filtrados[col].value_counts())

estu_tipodocumento
TI     852248
CC     161896
CR       2962
CE       2004
NES      1006
PEP       428
PE        172
RC         38
V          14
CCB         8
PC          8
Name: count, dtype: int64
cole_area_ubicacion
URBANO    862338
RURAL     158446
Name: count, dtype: int64
cole_bilingue
N           849330
Faltante    161282
S            10172
Name: count, dtype: int64
cole_calendario
A       1013406
OTRO       5390
B          1988
Name: count, dtype: int64
cole_caracter
ACADÉMICO            557152
TÉCNICO/ACADÉMICO    340630
TÉCNICO              110026
NO APLICA             12976
Name: count, dtype: int64
cole_genero
MIXTO        987182
FEMENINO      26052
MASCULINO      7550
Name: count, dtype: int64
cole_jornada
MAÑANA      486560
COMPLETA    171900
UNICA       128200
TARDE       111998
SABATINA     64976
NOCHE        57150
Name: count, dtype: int64
cole_naturaleza
OFICIAL       779258
NO OFICIAL    241526
Name: count, dtype: int64
estu_depto_reside
BOGOTÁ             159854
ANTIOQUIA          138582
VALLE               72446
CUNDINAMARCA        68190
ATLANTICO           59670
SANTANDER           47910
BOLIVAR             45746
CORDOBA             37804
BOYACA              31946
TOLIMA              30892
NARIÑO              30672
MAGDALENA           30476
NORTE SANTANDER     30190
HUILA               26212
CAUCA               25192
CESAR               24614
META                23376
SUCRE               20284
RISARALDA           20218
CALDAS              19746
LA GUAJIRA          15940
QUINDIO             11814
CASANARE            11288
CHOCO                8764
CAQUETA              8622
PUTUMAYO             7262
ARAUCA               6388
GUAVIARE             1874
AMAZONAS             1402
SAN ANDRES           1190
VICHADA               932
VAUPES                558
GUAINIA               490
EXTRANJERO            240
Name: count, dtype: int64
estu_genero
F    553090
M    467694
Name: count, dtype: int64
fami_cuartoshogar
Tres          412164
Dos           358882
Cuatro        133978
Uno            52276
Cinco          41342
Seis o mas     22142
Name: count, dtype: int64
fami_educacionmadre
Secundaria (Bachillerato) completa      272116
Primaria incompleta                     157038
Secundaria (Bachillerato) incompleta    151104
Educación profesional completa          107930
Técnica o tecnológica completa          105286
Primaria completa                       105140
Técnica o tecnológica incompleta         31628
Educación profesional incompleta         24602
Ninguno                                  24218
Postgrado                                21468
No sabe                                  18164
No Aplica                                 2090
Name: count, dtype: int64
fami_educacionpadre
Secundaria (Bachillerato) completa      235928
Primaria incompleta                     199176
Secundaria (Bachillerato) incompleta    141040
Primaria completa                       106636
Educación profesional completa           91860
Técnica o tecnológica completa           70272
No sabe                                  63432
Ninguno                                  38420
Técnica o tecnológica incompleta         21646
Educación profesional incompleta         20106
Postgrado                                18732
No Aplica                                13536
Name: count, dtype: int64
fami_estratovivienda
Estrato 2    409802
Estrato 1    319354
Estrato 3    216848
Estrato 4     51430
Estrato 5     15970
Estrato 6      7380
Name: count, dtype: int64
fami_personashogar
3 a 4      506636
5 a 6      322610
7 a 8       84230
1 a 2       74506
9 o más     32802
Name: count, dtype: int64
fami_tieneautomovil
No    777336
Si    243448
Name: count, dtype: int64
fami_tienecomputador
Si    581910
No    438874
Name: count, dtype: int64
fami_tieneinternet
Si    624932
No    395852
Name: count, dtype: int64
fami_tienelavadora
Si    789150
No    231634
Name: count, dtype: int64
desemp_ingles
A-    492006
A1    293300
A2    153584
B1     67588
B+     14306
Name: count, dtype: int64

In [11]:
datos_finales = datos_filtrados.copy()
datos_finales['estu_tipodocumento'] = datos_filtrados['estu_tipodocumento'].apply(
    lambda x: x if x in ['CC', 'TI'] else 'Otro'
)

In [12]:
datos_modelo = datos_finales.copy()
datos_modelo = datos_modelo.drop(columns=['cole_bilingue', 'cole_caracter', 'punt_global'])
datos_modelo

,estu_tipodocumento,cole_area_ubicacion,cole_calendario,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,Ingresa,estu_edad
0,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,19.00
1,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,19.00
2,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,19.00
3,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,19.00
4,CC,URBANO,A,MIXTO,UNICA,OFICIAL,VALLE,F,Dos,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,No,No,No,A2,1,19.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,A,MIXTO,SABATINA,OFICIAL,TOLIMA,F,Tres,Primaria incompleta,Ninguno,Estrato 2,5 a 6,No,Si,Si,Si,A-,0,18.00
1027080,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,17.00
1027081,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,17.00
1027082,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,19.00
1027083,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,19.00

In [13]:
datos_modelo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1020784 entries, 0 to 1027083
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   estu_tipodocumento    1020784 non-null  object
 1   cole_area_ubicacion   1020784 non-null  object
 2   cole_calendario       1020784 non-null  object
 3   cole_genero           1020784 non-null  object
 4   cole_jornada          1020784 non-null  object
 5   cole_naturaleza       1020784 non-null  object
 6   estu_depto_reside     1020784 non-null  object
 7   estu_genero           1020784 non-null  object
 8   fami_cuartoshogar     1020784 non-null  object
 9   fami_educacionmadre   1020784 non-null  object
 10  fami_educacionpadre   1020784 non-null  object
 11  fami_estratovivienda  1020784 non-null  object
 12  fami_personashogar    1020784 non-null  object
 13  fami_tieneautomovil   1020784 non-null  object
 14  fami_tienecomputador  1020784 non-null  object
 15  fami_tieneinternet    1020784 non-null  object
 16  fami_tienelavadora    1020784 non-null  object
 17  desemp_ingles         1020784 non-null  object
 18  Ingresa               1020784 non-null  int64
 19  estu_edad             1020784 non-null  float64
dtypes: float64(1), int64(1), object(18)
memory usage: 163.5+ MB

## Fuentes de modelización

In [14]:
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn.model_selection import ParameterGrid, ParameterSampler
import mlflow
import keras
from keras import callbacks
from joblib import dump

In [15]:
# Instanciar el scaler
scaler = StandardScaler()

# Escalar solo col1 y col2
datos_modelo['estu_edad'] = scaler.fit_transform(datos_modelo[['estu_edad']])
#dump(scaler, 'scaler.pkl')
datos_modelo

,estu_tipodocumento,cole_area_ubicacion,cole_calendario,cole_genero,cole_jornada,cole_naturaleza,estu_depto_reside,estu_genero,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,Ingresa,estu_edad
0,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,0.63
1,CC,URBANO,A,MIXTO,TARDE,OFICIAL,BOGOTÁ,F,Dos,Técnica o tecnológica completa,Técnica o tecnológica completa,Estrato 2,1 a 2,Si,Si,Si,Si,A1,0,0.63
2,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,0.63
3,TI,URBANO,A,MIXTO,MAÑANA,OFICIAL,PUTUMAYO,F,Cuatro,Primaria incompleta,Primaria incompleta,Estrato 1,7 a 8,No,Si,Si,Si,A1,0,0.63
4,CC,URBANO,A,MIXTO,UNICA,OFICIAL,VALLE,F,Dos,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,No,No,No,A2,1,0.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,TI,URBANO,A,MIXTO,SABATINA,OFICIAL,TOLIMA,F,Tres,Primaria incompleta,Ninguno,Estrato 2,5 a 6,No,Si,Si,Si,A-,0,0.18
1027080,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,-0.27
1027081,TI,URBANO,A,MIXTO,UNICA,OFICIAL,CALDAS,F,Tres,Primaria incompleta,Primaria incompleta,Estrato 2,3 a 4,No,No,No,No,A-,0,-0.27
1027082,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,0.63
1027083,CC,URBANO,A,MIXTO,COMPLETA,NO OFICIAL,BOGOTÁ,F,Tres,Técnica o tecnológica completa,Técnica o tecnológica incompleta,Estrato 3,3 a 4,Si,Si,Si,Si,A2,0,0.63

In [16]:
y = datos_modelo['Ingresa']
datos_X = datos_modelo.drop(columns=['Ingresa'])

In [17]:
X = pd.get_dummies(datos_X, drop_first = True, dtype = int)
#dump(X.columns.to_list(), 'X_columns.pkl')

X

,estu_edad,estu_tipodocumento_Otro,estu_tipodocumento_TI,cole_area_ubicacion_URBANO,cole_calendario_B,cole_calendario_OTRO,cole_genero_MASCULINO,cole_genero_MIXTO,cole_jornada_MAÑANA,cole_jornada_NOCHE,...,fami_personashogar_7 a 8,fami_personashogar_9 o más,fami_tieneautomovil_Si,fami_tienecomputador_Si,fami_tieneinternet_Si,fami_tienelavadora_Si,desemp_ingles_A1,desemp_ingles_A2,desemp_ingles_B+,desemp_ingles_B1
0,0.63,0,0,1,0,0,0,1,0,0,...,0,0,1,1,1,1,1,0,0,0
1,0.63,0,0,1,0,0,0,1,0,0,...,0,0,1,1,1,1,1,0,0,0
2,0.63,0,1,1,0,0,0,1,1,0,...,1,0,0,1,1,1,1,0,0,0
3,0.63,0,1,1,0,0,0,1,1,0,...,1,0,0,1,1,1,1,0,0,0
4,0.63,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027079,0.18,0,1,1,0,0,0,1,0,0,...,0,0,0,1,1,1,0,0,0,0
1027080,-0.27,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1027081,-0.27,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1027082,0.63,0,0,1,0,0,0,1,0,0,...,0,0,1,1,1,1,0,1,0,0
1027083,0.63,0,0,1,0,0,0,1,0,0,...,0,0,1,1,1,1,0,1,0,0

In [18]:
import numpy as np
from sklearn.utils.class_weight import compute_class_weight

compute_class_weight(class_weight="balanced", classes=np.unique(y), y=y)

array([0.60384127, 2.90752071])

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
from sklearn.utils import class_weight
import numpy as np

# Asegúrate de que y_train sea un array plano (no one-hot)
y_train_np = np.array(y_train)

# Calcula los pesos de clase
class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_np),
    y=y_train_np
)

# Lo convierte a diccionario: {0: peso_0, 1: peso_1}
class_weights_dict = dict(enumerate(class_weights))
print(class_weights_dict)

{0: 0.6037496894850776, 1: 2.9096457660816215}

In [22]:
def train_model(parameters, train_X, train_y, test_X, test_y, experiment_name, early_stop):
    
    model = Sequential()
    model.add(Input(shape=(train_X.shape[1],)))
    model.add(Dense(parameters['hidden_units'], activation = parameters['act_func']))
    
    if parameters['layers'] > 1:
        model.add(Dense(parameters['hidden_units'], activation = parameters['act_func']))
    if parameters['layers'] == 3:
        model.add(Dense(parameters['hidden_units'], activation = parameters['act_func']))
        
    model.add(Dense(1, activation='sigmoid'))
    
    if parameters['optimizer'] == 'adam':
        opt = keras.optimizers.Adam(learning_rate = parameters['learning_rate'])
    elif parameters['optimizer'] == 'adagrad':
        opt = keras.optimizers.Adagrad(learning_rate = parameters['learning_rate'])
    elif parameters['optimizer'] == 'sgd':
        opt = keras.optimizers.SGD(learning_rate = parameters['learning_rate'])
    
    model.compile(optimizer = opt, loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    # defina el servidor para llevar el registro de modelos y artefactos
    mlflow.set_tracking_uri('http://127.0.0.1:5000')
    # registre el experimento
    experiment = mlflow.set_experiment(experiment_name)
    
    # Aquí se ejecuta MLflow sin especificar un nombre o id del experimento. MLflow los crea un experimento para este cuaderno por defecto y guarda las características del experimento y las métricas definidas. 
    # Para ver el resultado de las corridas haga click en Experimentos en el menú izquierdo. 
    with mlflow.start_run(experiment_id=experiment.experiment_id):
        
        history = model.fit(train_X, train_y,
                  epochs = parameters['epochs'],
                  batch_size = parameters['batch_size'],
                  validation_split = 0.2,
                  callbacks = [early_stop],
                  class_weight = class_weights_dict,
                  verbose = 0
                  )
        
        #Evaluar el modelo
        eval_model = model.evaluate(test_X, test_y, verbose = 0)
        loss = eval_model[0]
        accuracy = eval_model[1]
        
        y_pred_proba = model.predict(test_X)
        y_pred = (y_pred_proba >= parameters['threshold']).astype(int)
        
        cm = confusion_matrix(test_y, y_pred)
        
        tn = cm[0][0]
        tp = cm[1][1]
        fn = cm[1][0]
        fp = cm[0][1]
        
        pos_precision = tp / (tp + fp) if (tp + fp) != 0 else 0
        neg_precision = tn / (tn + fn) if (tn + fn) != 0 else 0
        pos_recall = tp / (tp + fn) if (tp + fn) != 0 else 0
        neg_recall = tn / (tn + fp) if (tn + fp) != 0 else 0
        error_I = fp / (fp + tn) if (fp + tn) != 0 else 0
        error_II = fn / (fn + tp) if (fn + tp) != 0 else 0
        
        # Log parameters and results
        mlflow.log_params(parameters)
        mlflow.log_metric("accuracy", round(accuracy, 5))
        mlflow.log_metric("test_loss", round(loss, 5))
        mlflow.log_metric("positive_precision", round(pos_precision, 5))
        mlflow.log_metric("negative_precision", round(neg_precision, 5))
        mlflow.log_metric("positive_recall", round(pos_recall, 5))
        mlflow.log_metric("negative_recall", round(neg_recall, 5))
        mlflow.log_metric("Error_I", round(error_I, 5))
        mlflow.log_metric("Error_II", round(error_II, 5))
        print(f'Loss: {loss}, Accuracy: {accuracy}')
        
        # Log model
        mlflow.tensorflow.log_model(model, "model")
            
    
        return {"model": model, 'history' : history}

In [ ]:
def show_history(history):
    plt.plot(hist.history['loss'], label='Entrenamiento')
    plt.plot(hist.history['val_loss'], label='Validación')
    plt.xlabel('Época')
    plt.ylabel('Precisión')
    plt.legend()
    plt.grid(True)
    plt.show()

In [23]:
def param_tuning(param_grid, nombre_prueba):
    earlystopping = callbacks.EarlyStopping(monitor = "val_loss",
                                        mode = "min",
                                        patience = 5,
                                        restore_best_weights = True)
    
    mod_hist = []
    for params in param_grid:
        models = []
        modelo = train_model(params, X_train, y_train, X_test, y_test, nombre_prueba, earlystopping)
        models.append(modelo['model'])
        models.append(modelo['history'])
        mod_hist.append(models)
    
    return mod_hist

In [27]:
param_grid = {
    'act_func': ['relu', 'tanh', 'selu'],
    'batch_size': [32, 64, 128],
    'epochs': [10, 30, 50, 100],
    'optimizer': ['adam', 'adagrad', 'sgd'],
    'learning_rate': [0.0001, 0.001, 0.01, 0.1],
    'layers': [2, 3, 4],
    'hidden_units': [64, 128, 256],
    'threshold': [0.55, 0.6, 0.65, 0.7]
}

In [28]:
n_iter = 50  # número de combinaciones a probar
random_params = ParameterSampler(param_grid, n_iter=n_iter)

In [29]:
models_layer_units = param_tuning(random_params, 'binary_prueba_random_umbral')

6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 331us/step

2025/05/22 18:11:26 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3303721845149994, Accuracy: 0.8564732074737549

2025/05/22 18:11:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run lyrical-lark-255 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/275748bf89b34d40a5b60b45d66ea78f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 298us/step

2025/05/22 18:12:36 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3365693986415863, Accuracy: 0.8575997948646545

2025/05/22 18:12:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run luxuriant-wren-635 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/c3a02eb2f486457596e9cfd381c4772a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 337us/step

2025/05/22 18:14:44 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.34486478567123413, Accuracy: 0.8539457321166992

2025/05/22 18:14:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run beautiful-steed-524 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/94301c38d12f438087731a27d390bc5a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 197us/step

2025/05/22 18:16:33 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.32997941970825195, Accuracy: 0.8581336736679077

2025/05/22 18:16:38 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run caring-worm-20 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/2d627e47ae324f6c9d3cb09dd80ccda8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 266us/step

2025/05/22 18:19:01 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3381929397583008, Accuracy: 0.8541857600212097

2025/05/22 18:19:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run powerful-moose-763 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/19f8ead97119438384543cf0e5ceed46
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 3s 449us/step

2025/05/22 18:21:54 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3360010087490082, Accuracy: 0.8557335734367371

2025/05/22 18:21:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run nervous-ram-329 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/5ac78b5e3ceb4b91a3acb494c2317a0c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 193us/step

2025/05/22 18:23:18 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.4888230860233307, Accuracy: 0.7948833703994751

2025/05/22 18:23:23 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run languid-rat-301 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/e71381554f504508a9daf78d6541604d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 211us/step

2025/05/22 18:24:56 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3620496392250061, Accuracy: 0.8437771201133728

2025/05/22 18:25:00 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run placid-finch-542 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/f5fbda0fdfc64d0bab075e0aca1ef9b2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 212us/step

2025/05/22 18:26:04 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.34956517815589905, Accuracy: 0.8618122339248657

2025/05/22 18:26:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run fortunate-shrike-504 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/9307b51033d44b56920b9362b82494f9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 193us/step

2025/05/22 18:26:27 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3401203155517578, Accuracy: 0.8563213348388672

2025/05/22 18:26:31 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run awesome-dog-867 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/f628bbb7d5814df985fe53777798630f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 271us/step

2025/05/22 18:27:41 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.45978474617004395, Accuracy: 0.827529788017273

2025/05/22 18:27:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run bemused-goat-528 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/d555582b39a449faaa689347c514358a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 197us/step

2025/05/22 18:28:40 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.2939640283584595, Accuracy: 0.8751108050346375

2025/05/22 18:28:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run capricious-skunk-163 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/1dbe7331f2d34c9c852c26e085749649
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 262us/step

2025/05/22 18:29:38 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.34172430634498596, Accuracy: 0.8520991206169128

2025/05/22 18:29:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run charming-mare-2 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/417c5f08207544458353494a264ffce9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 327us/step

2025/05/22 18:32:39 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.6535287499427795, Accuracy: 0.827529788017273

2025/05/22 18:32:43 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run nebulous-ant-921 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/5a7fc4183c5543ad9ed22d673643e6b4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 225us/step

2025/05/22 18:33:37 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.6402691006660461, Accuracy: 0.827529788017273

2025/05/22 18:33:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run handsome-elk-953 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/f27b1e127b214e6e830c33925385fbd8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 358us/step

2025/05/22 18:35:36 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.38652023673057556, Accuracy: 0.8459665775299072

2025/05/22 18:35:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run nebulous-cod-993 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/e30f814bfe884df398874ed6c0e15bac
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 266us/step

2025/05/22 18:43:47 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3592762053012848, Accuracy: 0.8459519147872925

2025/05/22 18:43:52 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run brawny-newt-128 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/ecf263c9247e45cc9faeed7dc1a0cc6b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 264us/step

2025/05/22 18:46:36 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3167840242385864, Accuracy: 0.8496206402778625

2025/05/22 18:46:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run delicate-hound-262 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/b4f955f545e74e0395c6f6eb49c10565
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 250us/step

2025/05/22 18:47:55 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3547601103782654, Accuracy: 0.8461869955062866

2025/05/22 18:47:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run skillful-crow-312 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/f4336137a030469e8b789f615f1105aa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 341us/step

2025/05/22 18:48:51 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.35255345702171326, Accuracy: 0.8488907814025879

2025/05/22 18:48:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run fearless-rat-339 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/223f59e15ad440f8bc848b8dc312af0a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 248us/step

2025/05/22 18:52:21 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.36720243096351624, Accuracy: 0.8429346084594727

2025/05/22 18:52:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run sassy-crow-611 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/2115b729fc734562b34989a3b5919fe6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 213us/step

2025/05/22 19:15:41 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3745311200618744, Accuracy: 0.8443795442581177

2025/05/22 19:15:46 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run angry-perch-464 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/50e6e2ff20964cd799cfaf6d9a332426
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 237us/step

2025/05/22 19:16:51 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.33701586723327637, Accuracy: 0.8547098636627197

2025/05/22 19:16:55 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run handsome-gnat-397 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/edb9d85bd8fd4563afaa65c034ef4ab7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 202us/step

2025/05/22 19:18:10 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.34919652342796326, Accuracy: 0.8492434620857239

2025/05/22 19:18:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run gregarious-fish-180 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/a372517f5d584ab2b16f2dc713c0044a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 270us/step

2025/05/22 19:19:50 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.33481165766716003, Accuracy: 0.8559098839759827

2025/05/22 19:19:54 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run spiffy-mouse-828 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/d5475921fc3f453daa2d4556526ff229
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 245us/step

2025/05/22 19:22:06 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3278515338897705, Accuracy: 0.8588880300521851

2025/05/22 19:22:10 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run likeable-auk-857 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/45e5a0d2293a4633b5b39228ff1127cf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 271us/step

2025/05/22 19:23:05 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.33151090145111084, Accuracy: 0.8565711975097656

2025/05/22 19:23:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run beautiful-steed-423 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/ccc9fcf6a6f948c58088cee8a625048b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 197us/step

2025/05/22 19:23:53 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3592662811279297, Accuracy: 0.8468678593635559

2025/05/22 19:23:57 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run bedecked-mule-546 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/08c44064c1434de89ce8dbe28f6d87ee
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 225us/step

2025/05/22 19:25:35 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.33201295137405396, Accuracy: 0.8475437760353088

2025/05/22 19:25:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run nimble-panda-488 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/5e65654ef48741a5af34ce7313b5f043
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 272us/step

2025/05/22 19:27:03 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.4113372266292572, Accuracy: 0.8392952680587769

2025/05/22 19:27:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run rumbling-chimp-346 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/cf644d8547d84ccaad819ffa033166cd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 212us/step

2025/05/22 19:28:15 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.338311105966568, Accuracy: 0.852236270904541

2025/05/22 19:28:20 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run dapper-goat-884 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/767067b617f14692b33760696488d72d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 282us/step

2025/05/22 19:29:22 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3444504737854004, Accuracy: 0.8536028861999512

2025/05/22 19:29:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run selective-bat-697 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/de7babe15fa447cd879942bfe1070121
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 209us/step

2025/05/22 19:32:08 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.391580194234848, Accuracy: 0.8389572501182556

2025/05/22 19:32:14 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run spiffy-wren-762 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/b060b568159240439eee001fd7e74f24
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 208us/step

2025/05/22 19:33:12 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3285900950431824, Accuracy: 0.8593778610229492

2025/05/22 19:33:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run smiling-wolf-775 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/eb0fb3f21aa0460889c25810c5e178bc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 3s 453us/step

2025/05/22 19:35:46 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.34151285886764526, Accuracy: 0.8533628582954407

2025/05/22 19:35:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run stylish-gnu-618 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/03c5447e995d4d7dab8fdcb5a4012311
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 207us/step

2025/05/22 19:37:20 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3386285901069641, Accuracy: 0.8542004227638245

2025/05/22 19:37:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run bedecked-ray-926 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/7edb7f2532f14ebe86c4836725353a74
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 181us/step

2025/05/22 19:38:27 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.34865859150886536, Accuracy: 0.8501545190811157

2025/05/22 19:38:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run respected-toad-692 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/ef0bac1aca5145e8be2c61d1ff2175ca
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 223us/step

2025/05/22 19:39:18 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3460664749145508, Accuracy: 0.8496500253677368

2025/05/22 19:39:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run amazing-goat-289 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/1c3f0e0c53b64c66bd3dcd6a4e7cf9f5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 196us/step

2025/05/22 19:40:29 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.30465200543403625, Accuracy: 0.8654320240020752

2025/05/22 19:40:33 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run enthused-goose-678 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/b409427ac99e4ada9309eaf8744ee2f1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 212us/step

2025/05/22 19:41:11 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.35921546816825867, Accuracy: 0.846235990524292

2025/05/22 19:41:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run indecisive-worm-410 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/1795b005a939420faafd7782b7cf9b65
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 208us/step

2025/05/22 19:45:19 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.365313857793808, Accuracy: 0.8446440696716309

2025/05/22 19:45:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run mysterious-bug-998 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/2d237abead1c4257bdb61eb77c6ebf72
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 291us/step

2025/05/22 19:46:36 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.34825173020362854, Accuracy: 0.8533481359481812

2025/05/22 19:46:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run caring-quail-38 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/2e93b0164f8546b3b4999a30b4eb2a8b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 203us/step

2025/05/22 19:48:16 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.4863051176071167, Accuracy: 0.7901957631111145

2025/05/22 19:48:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run agreeable-perch-113 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/9b32bfed434945fda2df8404367b3a3c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 206us/step

2025/05/22 19:49:03 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3450894355773926, Accuracy: 0.8528828024864197

2025/05/22 19:49:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run secretive-crab-868 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/010f172b203d49e5811dfd6f5ae5423b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 196us/step

2025/05/22 19:49:37 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.35906827449798584, Accuracy: 0.8436497449874878

2025/05/22 19:49:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run nosy-crow-165 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/536ae4c8c186453b9d86cac39558a52a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 217us/step

2025/05/22 19:54:31 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.37593361735343933, Accuracy: 0.8445118069648743

2025/05/22 19:54:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run nimble-fawn-16 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/29a7994e01664e7a8e6002f44fecb8ce
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 195us/step

2025/05/22 19:54:55 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3258104622364044, Accuracy: 0.859157383441925

2025/05/22 19:54:59 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run melodic-cub-505 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/249d967691d049ee821145e7dc1ef621
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 212us/step

2025/05/22 19:56:37 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3842702805995941, Accuracy: 0.8390944004058838

2025/05/22 19:56:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run worried-mare-855 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/b6227c622fb64504b19d2a98215c4cea
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 2s 297us/step

2025/05/22 19:57:47 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3313077390193939, Accuracy: 0.8586921095848083

2025/05/22 19:57:51 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run delicate-ram-945 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/f7969cc3e76746f89affd62c011d7b6b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864
6380/6380 ━━━━━━━━━━━━━━━━━━━━ 1s 224us/step

2025/05/22 19:58:20 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.

Loss: 0.3336424231529236, Accuracy: 0.8587753772735596

2025/05/22 19:58:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

🏃 View run bemused-frog-686 at: http://127.0.0.1:5000/#/experiments/202826598519623864/runs/68c079ac1757477cb3d0e7703317e8d7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/202826598519623864